version: "3.9"

services:
  django:
    image: neko-scholar:1.0.0
    build: .
    command: bash -c "python manage.py makemigrations accounts && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"